spring.profiles.active=prod
logging.level.org.springframework=debug
currency-service.url=http://default.in28minutes.com
currency-service.key=defaultKey
currency-service.username=defaultUsername
management.endpoints.web.exposure.include=*