logging.level.org.springframework=trace
currency-service.url=http://dev.in28minutes.com
currency-service.key=devKey
currency-service.username=devUsername
management.endpoints.web.exposure.include=metrics,health