spring.application.name=database-demo

# Treat the word USER as a normal identifier, not a reserved SQL keyword
spring.datasource.url=jdbc:h2:mem:testdb;NON_KEYWORDS=USER;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Required if you use schema.sql or data.sql
spring.jpa.defer-datasource-initialization=true

# This forces Spring Boot to run: schema.sql and data.sql before your application starts.
# spring.sql.init.mode=always

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=DEBUG

#logging.level.root=debug
#logging.level.org.springframework=debug
